
package com.sqlserver.ssrs.reportingservice2005;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * The Reporting Services Web Service enables you to manage a report server and its contents including server settings, security, reports, subscriptions, and data sources.
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ReportingService2005", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", wsdlLocation = "file:/C:/code/ecoo/ssrs-api/src/main/resources/reportService2005.wsdl")
public class ReportingService2005
    extends Service
{

    private final static URL REPORTINGSERVICE2005_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sqlserver.ssrs.reportingservice2005.ReportingService2005 .class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sqlserver.ssrs.reportingservice2005.ReportingService2005 .class.getResource(".");
            url = new URL(baseUrl, "file:/C:/code/ecoo/ssrs-api/src/main/resources/reportService2005.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/code/ecoo/ssrs-api/src/main/resources/reportService2005.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        REPORTINGSERVICE2005_WSDL_LOCATION = url;
    }

    public ReportingService2005(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReportingService2005() {
        super(REPORTINGSERVICE2005_WSDL_LOCATION, new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportingService2005"));
    }

    /**
     * 
     * @return
     *     returns ReportingService2005Soap
     */
    @WebEndpoint(name = "ReportingService2005Soap")
    public ReportingService2005Soap getReportingService2005Soap() {
        return super.getPort(new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportingService2005Soap"), ReportingService2005Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReportingService2005Soap
     */
    @WebEndpoint(name = "ReportingService2005Soap")
    public ReportingService2005Soap getReportingService2005Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", "ReportingService2005Soap"), ReportingService2005Soap.class, features);
    }

}
