
package com.sqlserver.ssrs.reportingservice2005;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 */
@WebService(name = "ReportExecutionServiceSoap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
@XmlSeeAlso({
        ObjectFactory.class, ExecutionHeader.class
})
public interface ReportExecutionServiceSoap {


    /**
     * @return returns com.sqlserver.ssrs.reportingservice2005.ArrayOfString
     */
    @WebMethod(operationName = "ListSecureMethods", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ListSecureMethods")
    @WebResult(name = "ListSecureMethodsResult", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ListSecureMethods", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.ListSecureMethods")
    @ResponseWrapper(localName = "ListSecureMethodsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.ListSecureMethodsResponse")
    public ArrayOfString listSecureMethods();

    /**
     * @param historyID
     * @param report
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo
     */
    @WebMethod(operationName = "LoadReport", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadReport", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadReport")
    @ResponseWrapper(localName = "LoadReportResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadReportResponse")
    public ExecutionInfo loadReport(
            @WebParam(name = "Report", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String report,
            @WebParam(name = "HistoryID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String historyID);

    /**
     * @param historyID
     * @param report
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo2
     */
    @WebMethod(operationName = "LoadReport2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReport2")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadReport2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadReport2")
    @ResponseWrapper(localName = "LoadReport2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadReport2Response")
    public ExecutionInfo2 loadReport2(
            @WebParam(name = "Report", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String report,
            @WebParam(name = "HistoryID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String historyID);

    /**
     * @param executionInfo
     * @param warnings
     * @param definition
     */
    @WebMethod(operationName = "LoadReportDefinition", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition")
    @RequestWrapper(localName = "LoadReportDefinition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadReportDefinition")
    @ResponseWrapper(localName = "LoadReportDefinitionResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadReportDefinitionResponse")
    public void loadReportDefinition(
            @WebParam(name = "Definition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    byte[] definition,
            @WebParam(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<ExecutionInfo> executionInfo,
            @WebParam(name = "warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<ArrayOfWarning> warnings);

    /**
     * @param executionInfo
     * @param warnings
     * @param definition
     */
    @WebMethod(operationName = "LoadReportDefinition2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadReportDefinition2")
    @RequestWrapper(localName = "LoadReportDefinition2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadReportDefinition2")
    @ResponseWrapper(localName = "LoadReportDefinition2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadReportDefinition2Response")
    public void loadReportDefinition2(
            @WebParam(name = "Definition", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    byte[] definition,
            @WebParam(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<ExecutionInfo2> executionInfo,
            @WebParam(name = "warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<ArrayOfWarning> warnings);

    /**
     * @param credentials
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo
     */
    @WebMethod(operationName = "SetExecutionCredentials", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionCredentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.SetExecutionCredentials")
    @ResponseWrapper(localName = "SetExecutionCredentialsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.SetExecutionCredentialsResponse")
    public ExecutionInfo setExecutionCredentials(
            @WebParam(name = "Credentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    ArrayOfDataSourceCredentials credentials);

    /**
     * @param credentials
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo2
     */
    @WebMethod(operationName = "SetExecutionCredentials2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionCredentials2")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionCredentials2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.SetExecutionCredentials2")
    @ResponseWrapper(localName = "SetExecutionCredentials2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.SetExecutionCredentials2Response")
    public ExecutionInfo2 setExecutionCredentials2(
            @WebParam(name = "Credentials", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    ArrayOfDataSourceCredentials credentials);

    /**
     * @param parameterLanguage
     * @param parameters
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo
     */
    @WebMethod(operationName = "SetExecutionParameters", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionParameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.SetExecutionParameters")
    @ResponseWrapper(localName = "SetExecutionParametersResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.SetExecutionParametersResponse")
    public ExecutionInfo setExecutionParameters(
            @WebParam(name = "Parameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    ArrayOfParameterValue parameters,
            @WebParam(name = "ParameterLanguage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String parameterLanguage);

    /**
     * @param parameterLanguage
     * @param parameters
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo2
     */
    @WebMethod(operationName = "SetExecutionParameters2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/SetExecutionParameters2")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "SetExecutionParameters2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.SetExecutionParameters2")
    @ResponseWrapper(localName = "SetExecutionParameters2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.SetExecutionParameters2Response")
    public ExecutionInfo2 setExecutionParameters2(
            @WebParam(name = "Parameters", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    ArrayOfParameterValue parameters,
            @WebParam(name = "ParameterLanguage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String parameterLanguage);

    /**
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo
     */
    @WebMethod(operationName = "ResetExecution", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ResetExecution", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.ResetExecution")
    @ResponseWrapper(localName = "ResetExecutionResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.ResetExecutionResponse")
    public ExecutionInfo resetExecution();

    /**
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo2
     */
    @WebMethod(operationName = "ResetExecution2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ResetExecution2")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ResetExecution2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.ResetExecution2")
    @ResponseWrapper(localName = "ResetExecution2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.ResetExecution2Response")
    public ExecutionInfo2 resetExecution2();

    /**
     * @param result
     * @param extension
     * @param warnings
     * @param streamIds
     * @param format
     * @param mimeType
     * @param encoding
     * @param deviceInfo
     */
    @WebMethod(operationName = "Render", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Render")
    @RequestWrapper(localName = "Render", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.Render")
    @ResponseWrapper(localName = "RenderResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.RenderResponse")
    public void render(
            @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String format,
            @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String deviceInfo,
            @WebParam(name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<byte[]> result,
            @WebParam(name = "Extension", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> extension,
            @WebParam(name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> mimeType,
            @WebParam(name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> encoding,
            @WebParam(name = "Warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<ArrayOfWarning> warnings,
            @WebParam(name = "StreamIds", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<ArrayOfString> streamIds);

    /**
     * @param result
     * @param extension
     * @param warnings
     * @param streamIds
     * @param format
     * @param paginationMode
     * @param mimeType
     * @param encoding
     * @param deviceInfo
     */
    @WebMethod(operationName = "Render2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Render2")
    @RequestWrapper(localName = "Render2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.Render2")
    @ResponseWrapper(localName = "Render2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.Render2Response")
    public void render2(
            @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String format,
            @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String deviceInfo,
            @WebParam(name = "PaginationMode", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    PageCountMode paginationMode,
            @WebParam(name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<byte[]> result,
            @WebParam(name = "Extension", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> extension,
            @WebParam(name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> mimeType,
            @WebParam(name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> encoding,
            @WebParam(name = "Warnings", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<ArrayOfWarning> warnings,
            @WebParam(name = "StreamIds", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<ArrayOfString> streamIds);

    /**
     * @param result
     * @param streamID
     * @param format
     * @param mimeType
     * @param encoding
     * @param deviceInfo
     */
    @WebMethod(operationName = "RenderStream", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/RenderStream")
    @RequestWrapper(localName = "RenderStream", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.RenderStream")
    @ResponseWrapper(localName = "RenderStreamResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.RenderStreamResponse")
    public void renderStream(
            @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String format,
            @WebParam(name = "StreamID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String streamID,
            @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String deviceInfo,
            @WebParam(name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<byte[]> result,
            @WebParam(name = "Encoding", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> encoding,
            @WebParam(name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> mimeType);

    /**
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo
     */
    @WebMethod(operationName = "GetExecutionInfo", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "GetExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.GetExecutionInfo")
    @ResponseWrapper(localName = "GetExecutionInfoResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.GetExecutionInfoResponse")
    public ExecutionInfo getExecutionInfo();

    /**
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo2
     */
    @WebMethod(operationName = "GetExecutionInfo2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetExecutionInfo2")
    @WebResult(name = "executionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "GetExecutionInfo2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.GetExecutionInfo2")
    @ResponseWrapper(localName = "GetExecutionInfo2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.GetExecutionInfo2Response")
    public ExecutionInfo2 getExecutionInfo2();

    /**
     * @return returns com.sqlserver.ssrs.reportingservice2005.DocumentMapNode
     */
    @WebMethod(operationName = "GetDocumentMap", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetDocumentMap")
    @WebResult(name = "result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "GetDocumentMap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.GetDocumentMap")
    @ResponseWrapper(localName = "GetDocumentMapResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.GetDocumentMapResponse")
    public DocumentMapNode getDocumentMap();

    /**
     * @param drillthroughID
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo
     */
    @WebMethod(operationName = "LoadDrillthroughTarget", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget")
    @WebResult(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadDrillthroughTarget", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadDrillthroughTarget")
    @ResponseWrapper(localName = "LoadDrillthroughTargetResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadDrillthroughTargetResponse")
    public ExecutionInfo loadDrillthroughTarget(
            @WebParam(name = "DrillthroughID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String drillthroughID);

    /**
     * @param drillthroughID
     * @return returns com.sqlserver.ssrs.reportingservice2005.ExecutionInfo2
     */
    @WebMethod(operationName = "LoadDrillthroughTarget2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LoadDrillthroughTarget2")
    @WebResult(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "LoadDrillthroughTarget2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadDrillthroughTarget2")
    @ResponseWrapper(localName = "LoadDrillthroughTarget2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LoadDrillthroughTarget2Response")
    public ExecutionInfo2 loadDrillthroughTarget2(
            @WebParam(name = "DrillthroughID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String drillthroughID);

    /**
     * @param toggleID
     * @return returns boolean
     */
    @WebMethod(operationName = "ToggleItem", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ToggleItem")
    @WebResult(name = "Found", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ToggleItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.ToggleItem")
    @ResponseWrapper(localName = "ToggleItemResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.ToggleItemResponse")
    public boolean toggleItem(
            @WebParam(name = "ToggleID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String toggleID);

    /**
     * @param docMapID
     * @return returns int
     */
    @WebMethod(operationName = "NavigateDocumentMap", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/NavigateDocumentMap")
    @WebResult(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "NavigateDocumentMap", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.NavigateDocumentMap")
    @ResponseWrapper(localName = "NavigateDocumentMapResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.NavigateDocumentMapResponse")
    public int navigateDocumentMap(
            @WebParam(name = "DocMapID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String docMapID);

    /**
     * @param bookmarkID
     * @param pageNumber
     * @param uniqueName
     */
    @WebMethod(operationName = "NavigateBookmark", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/NavigateBookmark")
    @RequestWrapper(localName = "NavigateBookmark", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.NavigateBookmark")
    @ResponseWrapper(localName = "NavigateBookmarkResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.NavigateBookmarkResponse")
    public void navigateBookmark(
            @WebParam(name = "BookmarkID", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String bookmarkID,
            @WebParam(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<Integer> pageNumber,
            @WebParam(name = "UniqueName", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> uniqueName);

    /**
     * @param startPage
     * @param findValue
     * @param endPage
     * @return returns int
     */
    @WebMethod(operationName = "FindString", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/FindString")
    @WebResult(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "FindString", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.FindString")
    @ResponseWrapper(localName = "FindStringResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.FindStringResponse")
    public int findString(
            @WebParam(name = "StartPage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    int startPage,
            @WebParam(name = "EndPage", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    int endPage,
            @WebParam(name = "FindValue", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String findValue);

    /**
     * @param numPages
     * @param pageNumber
     * @param clear
     * @param sortItem
     * @param reportItem
     * @param direction
     */
    @WebMethod(operationName = "Sort", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort")
    @RequestWrapper(localName = "Sort", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.Sort")
    @ResponseWrapper(localName = "SortResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.SortResponse")
    public void sort(
            @WebParam(name = "SortItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String sortItem,
            @WebParam(name = "Direction", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    SortDirectionEnum direction,
            @WebParam(name = "Clear", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    boolean clear,
            @WebParam(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<Integer> pageNumber,
            @WebParam(name = "ReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> reportItem,
            @WebParam(name = "NumPages", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<Integer> numPages);

    /**
     * @param pageNumber
     * @param executionInfo
     * @param clear
     * @param sortItem
     * @param paginationMode
     * @param reportItem
     * @param direction
     */
    @WebMethod(operationName = "Sort2", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Sort2")
    @RequestWrapper(localName = "Sort2", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.Sort2")
    @ResponseWrapper(localName = "Sort2Response", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.Sort2Response")
    public void sort2(
            @WebParam(name = "SortItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String sortItem,
            @WebParam(name = "Direction", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    SortDirectionEnum direction,
            @WebParam(name = "Clear", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    boolean clear,
            @WebParam(name = "PaginationMode", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    PageCountMode paginationMode,
            @WebParam(name = "PageNumber", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<Integer> pageNumber,
            @WebParam(name = "ReportItem", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> reportItem,
            @WebParam(name = "ExecutionInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<ExecutionInfo2> executionInfo);

    /**
     * @param result
     * @param format
     * @param mimeType
     * @param deviceInfo
     */
    @WebMethod(operationName = "GetRenderResource", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/GetRenderResource")
    @RequestWrapper(localName = "GetRenderResource", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.GetRenderResource")
    @ResponseWrapper(localName = "GetRenderResourceResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.GetRenderResourceResponse")
    public void getRenderResource(
            @WebParam(name = "Format", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String format,
            @WebParam(name = "DeviceInfo", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String deviceInfo,
            @WebParam(name = "Result", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<byte[]> result,
            @WebParam(name = "MimeType", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", mode = WebParam.Mode.OUT)
                    Holder<String> mimeType);

    /**
     * @return returns com.sqlserver.ssrs.reportingservice2005.ArrayOfExtension
     */
    @WebMethod(operationName = "ListRenderingExtensions", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/ListRenderingExtensions")
    @WebResult(name = "Extensions", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
    @RequestWrapper(localName = "ListRenderingExtensions", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.ListRenderingExtensions")
    @ResponseWrapper(localName = "ListRenderingExtensionsResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.ListRenderingExtensionsResponse")
    public ArrayOfExtension listRenderingExtensions();

    /**
     * @param password
     * @param authority
     * @param userName
     */
    @WebMethod(operationName = "LogonUser", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/LogonUser")
    @RequestWrapper(localName = "LogonUser", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LogonUser")
    @ResponseWrapper(localName = "LogonUserResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LogonUserResponse")
    public void logonUser(
            @WebParam(name = "userName", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String userName,
            @WebParam(name = "password", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String password,
            @WebParam(name = "authority", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices")
                    String authority);

    /**
     *
     */
    @WebMethod(operationName = "Logoff", action = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices/Logoff")
    @RequestWrapper(localName = "Logoff", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.Logoff")
    @ResponseWrapper(localName = "LogoffResponse", targetNamespace = "http://schemas.microsoft.com/sqlserver/2005/06/30/reporting/reportingservices", className = "com.sqlserver.ssrs.reportingservice2005.LogoffResponse")
    public void logoff();

}
